### PR TITLE
Use exports field to define cjs and esm files

### LINKED ISSUE #63: Cannot import from a Node.js ESM package
Consider the following simple package:
# `package.json`
```json
{
    "type": "module",
    "dependencies": {
        "wasm-feature-detect": "^1.5.0"
    }
}
```

# `index.js`
```js
import { simd } from "wasm-feature-detect";
console.log(simd);
```

Running the following:
```sh
npm install
node index.js
```
Should've output:
```
[AsyncFunction: simd]
```
But instead the following error is produced:
```
file:///.../index.js:1
import { simd } from "wasm-feature-detect";
         ^^^^
SyntaxError: Named export 'simd' not found. The requested module 'wasm-feature-detect' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'wasm-feature-detect';
const { simd } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)

Node.js v19.6.1
```

I suspect the problem resides in the following line:
https://github.com/GoogleChromeLabs/wasm-feature-detect/blob/d5b2de2f55736b6f82473afcdce8c59f76e42d5f/package.json#L6

According to https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions, the `"module"` field doesn't even exist, but `"exports"` does. Applying the following patch fixes the problem:
```diff
-  "module": "dist/esm/index.js",
+  "exports": "./dist/esm/index.js",
```

### PR DESCRIPTION
**Pull request by surma**
Fixes #63

### CODE REVIEW

**Comment by surma** [comment]
@relrelb can you give this branch a try to double check that I am not breaking anything?

**Comment by relrelb** [comment]
Looks good on my end (tried both ESM `import` and `require`). Thanks for the quick fix!

However, this might possibly break old Node.js versions; Quoting from https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions:
> ["main"](https://nodejs.org/api/packages.html#main) - The default module when loading the package, if exports is not specified, and in versions of Node.js prior to the introduction of exports.

So, if I understand correctly, without `"main"` Node.js versions which are not aware of `"exports"` (namely before v12.7.0) will not be able to figure out the entry point. This may be irrelevant but just worth mentioning.

**Comment by surma** [comment]
Node 12 has reached EOL. Node 14 reaches EOL in April. So I am okay with this :D Thanks for the check!!

**Comment by relrelb** [comment]
@surma Do you plan publishing a new release soon? I encountered this problem while working on another project, and kind of needing the fix...

**Comment by surma** [comment]
Just published in v1.5.1

**Pull request merged**
