### PR TITLE
Add detector for extended const proposal

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
Can you give me a pointer or two how how to run the tests?  (Perhaps I can document that in the README under `Contributing`)

**Comment by sbc100** [comment]
@dschuff

**Comment by dschuff** [comment]
you can do `npm run test` to run the tests (it just runs test/index.js in node). Other runnable commands/scripts can be found in package.json.

**Comment by sbc100** [comment]
> you can do `npm run test` to run the tests (it just runs test/index.js in node). Other runnable commands/scripts can be found in package.json.

OK that seems to work.. it reported that this feature was missing for me (probably because i'm on an old version of node).

**Comment by sbc100** [comment]
Confirmed it works:

```
$ node --experimental-wasm-extended-const test/index.js
...
The feature extendedConst returned: true
$ node test/index.js
...
The feature extendedConst returned: false
```

**Review by surma — APPROVED** [review]
Oh exciting proposal! Thanks for adding a detector!

**Comment by sbc100** [comment]
BTW, can we switch the primary branch from `master` to `main` here?  My fingers so used to main now :)

**Comment by surma** [comment]
Oh yeah you are right. Will do now

**Comment by sbc100** [comment]
And can we publish a new version to npm so that the website can start using it?  (sorry to bombard you with requests).

**Comment by surma** [comment]
I just published v1.3.0 :)

`main` now exists, but is not the default branch yet as I’m lacking permission to change it. I pinged folks to do this for me.

**Comment by surma** [comment]
I lied. `main` is now the default :)

**Pull request merged**
